[package]
name = "cogwheel-dns-core"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
hickory-proto.workspace = true
hickory-resolver.workspace = true
moka.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
cogwheel-policy = { path = "../cogwheel-policy" }
