[package]
name = "cogwheel-lists"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lints]
workspace = true

[dependencies]
base64.workspace = true
reqwest.workspace = true
serde.workspace = true
url.workspace = true
cogwheel-policy = { path = "../cogwheel-policy" }

[dev-dependencies]
tokio.workspace = true
