[package]
name = "cogwheel-server"
version = "0.1.0"
edition = "2024"
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
futures-util.workspace = true
url.workspace = true
cogwheel-dns-core = { path = "../../crates/cogwheel-dns-core" }
cogwheel-lists = { path = "../../crates/cogwheel-lists" }
cogwheel-policy = { path = "../../crates/cogwheel-policy" }
cogwheel-storage = { path = "../../crates/cogwheel-storage" }
